# System deployment tasks
- hosts: machines
  become: true
  gather_facts: true
  collections:
    - xstem.system
  roles:
    - { role: generic, tags: [ 'generic' ] }
    - { role: ssh, tags: [ 'ssh' ] }
    - { role: motd, tags: [ 'motd' ] }
  tags: [ 'deploy', 'system' ]
