---
# Copy motd template if defined
- name: Copy motd template if defined
  template:
    src: "{{ motd_template }}"
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
  when: motd_template is defined
  tags: [ 'motd' ]
